### ISSUE TITLE
If  no DOI SEO 's view not rendered - investigation article pid 8pGzPyTDKBjR not rendered

### ISSUE THREAD

**Issue by eliselavy** [C2DH/journal-of-digital-history-backend#116]
/journal-of-digital-history-backend/jdhseo/utils.py, line 227, in getDoiUrlDGFormatted

**Comment by eliselavy** [comment]
```
Error occurred on article pk=14 notebook remote_url=http://10.240.4.179/proxy-githubusercontent/jdh-observer/jdh001-8pGzPyTDKBjR/main/JDH_Article.ipynb
can only concatenate str (not "NoneType") to str
Traceback (most recent call last):
  File "/Users/elisabeth.guerard/c2dh/journal-of-digital-history-backend/jdhseo/views.py", line 61, in ArticleDetail
    context.update({'nb': parseJupyterNotebook(res.json(), contact_orcid)})
  File "/Users/elisabeth.guerard/c2dh/journal-of-digital-history-backend/jdhseo/utils.py", line 116, in parseJupyterNotebook
```
